name: Build Project

on:
  push:
    branches: 
      - master
      - development
      - 'feature/**'
      - 'refactor/**'

jobs:
  build:
    # this step builds the project using mvn package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache mvn dependencies
      uses: actions/cache@v2.1.4
      env:
        cache-name: mvn-deps
      with:
        path: ~/.m2
        key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ env.cache-name }}-
    - name: Build with Maven
      run: mvn -B kotlin:compile package --file pom.xml
