name: Java CI

on:
  pull_request:
  push:
    branches: 
      - master
      - development

jobs:
  style_check:
    # This job uses google-java-format to check whether the (main and test) source code is formatted properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download google-java-format Release 1.8
        run: wget https://github.com/google/google-java-format/releases/download/google-java-format-1.8/google-java-format-1.8-all-deps.jar
      - name: Check style with google-java-format
        # --dry-run lists all files that do NOT comply in either the main or the test source directories
        run: |
          if [[ $(java -jar google-java-format-1.8-all-deps.jar --dry-run src/*/java/**/*.java) ]]; then
            false
          else
            true
          fi
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven
      run: mvn -B kotlin:compile test --file pom.xml
    - name: Build with Maven
      run: mvn -B kotlin:compile package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Merkompiler-standalone.jar
        path: target/Merkompiler-jar-with-dependencies.jar
